version: '3.8'

services:
  wordpress:
    image: wordpress:php8.0-fpm-alpine
    container_name: "${PROJECT_NAME}_wordpress"
    restart: always
    volumes:
      - ${WORDPRESS_DATA_PATH}:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: "${PROJECT_NAME}_mariadb"
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  webserver:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${WORDPRESS_DATA_PATH}:/var/www/html:ro
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_phpmyadmin"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
  wordpress: