version: '3.8'

x-services-defaults:
  &service-defaults
  restart: always
  networks:
    - front

services:
  wordpress:
    <<: *service-defaults
    image: ${WORDPRESS_TAG}
    container_name: "${PROJECT_NAME}_wordpress"
    working_dir: /var/www/html
#    command: php-fpm80 -F -dzend.assertions=1 -dopcache.jit_buffer_size=20M
    environment:
      COMPOSER_MEMORY_LIMIT: "-1"
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/php/90-mail.ini:/etc/php8/conf.d/90-mail.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_wordpress.rule=Host(`${PROJECT_BASE_URL}`)"
    depends_on:
      - db

  mariadb:
    <<: *service-defaults
    image: ${MARIADB_TAG}
    container_name: "${PROJECT_NAME}_mariadb"
#    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  nginx:
    <<: *service-defaults
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${WORDPRESS_DATA_PATH}:/var/www/html:ro
    depends_on:
      - wordpress

  phpmyadmin:
    <<: *service-defaults
    image: ${PHPMYADMIN_TAG}
    container_name: "${PROJECT_NAME}_phpmyadmin"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
  wordpress:

networks:
  front:
    driver: bridge